mutation createTour(
  $travelSlug: String!
  $name: String!
  $startingDate: Timestamp!
  $endingDate: Timestamp!
  $price: Int!
) {
  createTour(
    travelSlug: $travelSlug
    createTourInput: {
      name: $name
      startingDate: $startingDate
      endingDate: $endingDate
      price: $price
    }
  ) {
    id
    name
    startingDate
    endingDate
    price
  }
}

mutation createTravel(
  $isPublic: Boolean!
  $slug: String!
  $name: String!
  $description: String!
  $numberOfDays: Int!
  $moods: MoodsInput!
) {
  createTravel(
    createTravelInput: {
      isPublic: $isPublic
      slug: $slug
      name: $name
      description: $description
      numberOfDays: $numberOfDays
      moods: $moods
    }
  ) {
    id
    isPublic
    slug
    name
    description
    numberOfDays
    moods {
      nature
      relax
      history
      culture
      party
    }
  }
}

mutation deleteTravel($slug: String!) {
  deleteTravel(slug: $slug) {
    id
    isPublic
    slug
    name
    description
    numberOfDays
    moods {
      nature
      relax
      history
      culture
      party
    }
  }
}

mutation login($email: String!, $password: String!) {
  login(input: { email: $email, password: $password }) {
    accessToken
  }
}

query tours(
  $travelSlug: String!
  $priceFrom: Int
  $priceTo: Int
  $startingDate: Timestamp
  $endingDate: Timestamp
  $priceSortOrder: SortOrder
  $skip: Int
  $take: Int
) {
  tours(
    findToursInput: {
      travelSlug: $travelSlug
      priceFrom: $priceFrom
      priceTo: $priceTo
      startingDate: $startingDate
      endingDate: $endingDate
      priceSortOrder: $priceSortOrder
      skip: $skip
      take: $take
    }
  ) {
    id
    name
    startingDate
    endingDate
    price
  }
}

query travels($skip: Int, $take: Int) {
  travels(findTravelsInput: { skip: $skip, take: $take }) {
    id
    isPublic
    slug
    name
    description
    numberOfDays
    moods {
      nature
      relax
      history
      culture
      party
    }
    tours {
      id
      name
      startingDate
      endingDate
      price
    }
  }
}
